FROM python:3.12

ENV PYTEST_RUNNING_IN_CONTAINER=1

COPY python-requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Add Docker's official GPG key
RUN apt update \
  && apt install -y \
    ca-certificates \
    curl \
  && install -m 0755 -d /etc/apt/keyrings \
  && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
  && chmod a+r /etc/apt/keyrings/docker.asc

# Add the Docker repository to Apt sources
RUN echo \
  "Types: deb\n \
  URIs: https://download.docker.com/linux/ubuntu\n \
  Suites: $(. /etc/os-release && echo \"$VERSION_CODENAME\")\n \
  Components: stable\n \
  Signed-By: /etc/apt/keyrings/docker.asc" \
  > /etc/apt/sources.list.d/docker.sources

# Install docker-ce-cli and docker-compose-plugin requirements for Pytest docker_compose fixture
RUN apt update \
  && apt install -y --no-install-recommends \
    docker-ce-cli \
    docker-compose-plugin \
  && apt clean \
  && rm -r /var/lib/apt/lists/*

# Check if docker compose is available
RUN docker compose version

WORKDIR /test
ENTRYPOINT ["pytest"]
