name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "**.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_docker_image: [alpine, debian]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
#          python -m pip install --upgrade pip
          uv pip install -r python-requirements.txt
        working-directory: test/requirements

      - name: Pull nginx:alpine image
        run: docker pull nginx:alpine

      - name: Build Docker web server image
        run: make build-webserver

      - name: Build Docker nginx proxy test image
        run: make build-nginx-proxy-test-${{ matrix.base_docker_image }}

      - name: Run tests
        run: uv pytest
        working-directory: test
