name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "**.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_docker_image: [alpine, debian]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-requirements.txt
        working-directory: test/requirements

      - name: Pull nginx:alpine image
        run: docker pull nginx:alpine

      - name: Build Docker web server image
        run: make build-webserver

      - name: Build Docker nginx proxy test image
        run: make build-nginx-proxy-test-${{ matrix.base_docker_image }}

      - name: Run tests
        run: pytest
        working-directory: test
